# Generated by Django 5.0.6 on 2025-10-24 14:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_availabilityslot_appointment_conversation_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicianDateOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['physician', 'date', 'start_time'],
                'indexes': [models.Index(fields=['physician', 'date'], name='core_physic_physici_a1aaad_idx')],
                'unique_together': {('physician', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='PhysicianWeeklyAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['physician', 'weekday', 'start_time'],
                'unique_together': {('physician', 'weekday', 'start_time', 'end_time')},
            },
        ),
    ]
