# Generated by Django 5.0.6 on 2025-10-24 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_physiciandateoverride_physicianweeklyavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicianweeklyavailability',
            name='snap_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Snap start times to this granularity.'),
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='FlexAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flex_appointments_as_patient', to=settings.AUTH_USER_MODEL)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flex_appointments_as_physician', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start'],
                'indexes': [models.Index(fields=['physician', 'start'], name='core_flexap_physici_5402c9_idx'), models.Index(fields=['patient', 'start'], name='core_flexap_patient_2412e7_idx'), models.Index(fields=['status'], name='core_flexap_status_4e2bf1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='flexappointment',
            constraint=models.CheckConstraint(check=models.Q(('end__gt', models.F('start'))), name='flexappt_end_gt_start'),
        ),
        migrations.AddIndex(
            model_name='timeoff',
            index=models.Index(fields=['physician', 'start'], name='core_timeof_physici_953859_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoff',
            index=models.Index(fields=['physician', 'end'], name='core_timeof_physici_0fcd32_idx'),
        ),
    ]
