# Generated by Django 5.0.6 on 2025-10-28 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_physicianweeklyavailability_snap_minutes_timeoff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='booked_by_flex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_slots', to='core.flexappointment'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['is_booked'], name='core_availa_is_book_60288d_idx'),
        ),
    ]
