# Generated by Django 5.0.6 on 2025-11-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_conversation_updated_at_message_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicianprofile',
            name='connect_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, unique=True),
        ),
    ]
